/**
 * FootballAI Digital NFT Cards Service
 * Database of 50 unique football player cards across Common, Rare, Epic, and Legendary tiers.
 * Model prepared for future smart contract minting and ERC-721 / ERC-1155 metadata standards.
 */

import { NFTCard, NFTRarity } from '../types';

const MOCK_CONTRACT = '0x742d35Cc6634C0532925a3b844Bc454e4438f44e';
const MOCK_CHAIN_ID = 8453; // Base / Optimism standard testnet

export const NFT_CARDS_DATA: NFTCard[] = [
  // 1-10: Legendary
  {
    tokenId: 1001,
    playerName: 'Kylian Mbappé',
    club: 'Real Madrid',
    nationality: 'France',
    rarity: 'Legendary',
    rating: 94,
    position: 'ST',
    pace: 97,
    shooting: 92,
    passing: 84,
    dribbling: 94,
    defending: 38,
    physical: 80,
    ability: 'Supersonic Sprint',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1001/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#01/100'
  },
  {
    tokenId: 1002,
    playerName: 'Erling Haaland',
    club: 'Manchester City',
    nationality: 'Norway',
    rarity: 'Legendary',
    rating: 93,
    position: 'ST',
    pace: 91,
    shooting: 95,
    passing: 70,
    dribbling: 82,
    defending: 45,
    physical: 92,
    ability: 'Cyborg Cannon',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1002/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#02/100'
  },
  {
    tokenId: 1003,
    playerName: 'Jude Bellingham',
    club: 'Real Madrid',
    nationality: 'England',
    rarity: 'Legendary',
    rating: 92,
    position: 'CAM',
    pace: 83,
    shooting: 88,
    passing: 89,
    dribbling: 90,
    defending: 78,
    physical: 84,
    ability: 'Clutch General',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1003/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#03/100'
  },
  {
    tokenId: 1004,
    playerName: 'Vinicius Jr.',
    club: 'Real Madrid',
    nationality: 'Brazil',
    rarity: 'Legendary',
    rating: 92,
    position: 'LW',
    pace: 96,
    shooting: 86,
    passing: 83,
    dribbling: 95,
    defending: 32,
    physical: 72,
    ability: 'Samba Flash',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1004/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#04/100'
  },
  {
    tokenId: 1005,
    playerName: 'Rodri Hernandez',
    club: 'Manchester City',
    nationality: 'Spain',
    rarity: 'Legendary',
    rating: 91,
    position: 'CDM',
    pace: 68,
    shooting: 82,
    passing: 91,
    dribbling: 85,
    defending: 89,
    physical: 88,
    ability: 'Metronome Shield',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1005/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#05/100'
  },
  {
    tokenId: 1006,
    playerName: 'Kevin De Bruyne',
    club: 'Manchester City',
    nationality: 'Belgium',
    rarity: 'Legendary',
    rating: 91,
    position: 'CM',
    pace: 74,
    shooting: 88,
    passing: 96,
    dribbling: 87,
    defending: 65,
    physical: 76,
    ability: 'Visionary Thread',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1006/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#06/100'
  },
  {
    tokenId: 1007,
    playerName: 'Mohamed Salah',
    club: 'Liverpool',
    nationality: 'Egypt',
    rarity: 'Legendary',
    rating: 91,
    position: 'RW',
    pace: 90,
    shooting: 90,
    passing: 84,
    dribbling: 89,
    defending: 45,
    physical: 78,
    ability: 'Pharaoh Curler',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1007/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#07/100'
  },
  {
    tokenId: 1008,
    playerName: 'Harry Kane',
    club: 'Bayern Munich',
    nationality: 'England',
    rarity: 'Legendary',
    rating: 91,
    position: 'ST',
    pace: 71,
    shooting: 94,
    passing: 86,
    dribbling: 84,
    defending: 50,
    physical: 83,
    ability: 'Apex Finisher',
    imageUrl: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1008/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#08/100'
  },
  {
    tokenId: 1009,
    playerName: 'Thibaut Courtois',
    club: 'Real Madrid',
    nationality: 'Belgium',
    rarity: 'Legendary',
    rating: 90,
    position: 'GK',
    pace: 52,
    shooting: 22,
    passing: 75,
    dribbling: 50,
    defending: 92,
    physical: 88,
    ability: 'Iron Fortress',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1009/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#09/100'
  },
  {
    tokenId: 1010,
    playerName: 'Lamine Yamal',
    club: 'Barcelona',
    nationality: 'Spain',
    rarity: 'Legendary',
    rating: 90,
    position: 'RW',
    pace: 93,
    shooting: 85,
    passing: 88,
    dribbling: 94,
    defending: 40,
    physical: 68,
    ability: 'Prodigy Arc',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1010/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#10/100'
  },

  // 11-25: Epic
  {
    tokenId: 1011,
    playerName: 'Bukayo Saka',
    club: 'Arsenal',
    nationality: 'England',
    rarity: 'Epic',
    rating: 89,
    position: 'RW',
    pace: 88,
    shooting: 86,
    passing: 85,
    dribbling: 90,
    defending: 64,
    physical: 76,
    ability: 'Starboy Surge',
    imageUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1011/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#11/250'
  },
  {
    tokenId: 1012,
    playerName: 'Florian Wirtz',
    club: 'Bayer Leverkusen',
    nationality: 'Germany',
    rarity: 'Epic',
    rating: 89,
    position: 'CAM',
    pace: 84,
    shooting: 84,
    passing: 90,
    dribbling: 91,
    defending: 52,
    physical: 70,
    ability: 'Maestro Symphony',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1012/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#12/250'
  },
  {
    tokenId: 1013,
    playerName: 'Lautaro Martínez',
    club: 'Inter Milan',
    nationality: 'Argentina',
    rarity: 'Epic',
    rating: 89,
    position: 'ST',
    pace: 83,
    shooting: 89,
    passing: 76,
    dribbling: 87,
    defending: 48,
    physical: 85,
    ability: 'El Toro Instinct',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1013/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#13/250'
  },
  {
    tokenId: 1014,
    playerName: 'Virgil van Dijk',
    club: 'Liverpool',
    nationality: 'Netherlands',
    rarity: 'Epic',
    rating: 89,
    position: 'CB',
    pace: 79,
    shooting: 60,
    passing: 73,
    dribbling: 72,
    defending: 91,
    physical: 88,
    ability: 'Colossus Aura',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1014/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#14/250'
  },
  {
    tokenId: 1015,
    playerName: 'William Saliba',
    club: 'Arsenal',
    nationality: 'France',
    rarity: 'Epic',
    rating: 88,
    position: 'CB',
    pace: 83,
    shooting: 40,
    passing: 76,
    dribbling: 76,
    defending: 89,
    physical: 84,
    ability: 'Lockdown Tackle',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1015/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#15/250'
  },
  {
    tokenId: 1016,
    playerName: 'Federico Valverde',
    club: 'Real Madrid',
    nationality: 'Uruguay',
    rarity: 'Epic',
    rating: 88,
    position: 'CM',
    pace: 89,
    shooting: 84,
    passing: 85,
    dribbling: 84,
    defending: 80,
    physical: 85,
    ability: 'Thunder Strike',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1016/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#16/250'
  },
  {
    tokenId: 1017,
    playerName: 'Declan Rice',
    club: 'Arsenal',
    nationality: 'England',
    rarity: 'Epic',
    rating: 88,
    position: 'CDM',
    pace: 75,
    shooting: 72,
    passing: 84,
    dribbling: 81,
    defending: 88,
    physical: 87,
    ability: 'Engine Room Interceptor',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1017/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#17/250'
  },
  {
    tokenId: 1018,
    playerName: 'Antoine Griezmann',
    club: 'Atletico Madrid',
    nationality: 'France',
    rarity: 'Epic',
    rating: 88,
    position: 'CAM',
    pace: 80,
    shooting: 88,
    passing: 88,
    dribbling: 88,
    defending: 68,
    physical: 74,
    ability: 'Spatial Architect',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1018/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#18/250'
  },
  {
    tokenId: 1019,
    playerName: 'Cole Palmer',
    club: 'Chelsea',
    nationality: 'England',
    rarity: 'Epic',
    rating: 87,
    position: 'CAM',
    pace: 82,
    shooting: 86,
    passing: 86,
    dribbling: 88,
    defending: 52,
    physical: 72,
    ability: 'Cold Blood Finish',
    imageUrl: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1019/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#19/250'
  },
  {
    tokenId: 1020,
    playerName: 'Phil Foden',
    club: 'Manchester City',
    nationality: 'England',
    rarity: 'Epic',
    rating: 88,
    position: 'RW',
    pace: 85,
    shooting: 85,
    passing: 87,
    dribbling: 91,
    defending: 56,
    physical: 66,
    ability: 'Pocket Dribble',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1020/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#20/250'
  },
  {
    tokenId: 1021,
    playerName: 'Jamal Musiala',
    club: 'Bayern Munich',
    nationality: 'Germany',
    rarity: 'Epic',
    rating: 88,
    position: 'CAM',
    pace: 85,
    shooting: 82,
    passing: 84,
    dribbling: 93,
    defending: 58,
    physical: 65,
    ability: 'Bambi Weave',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1021/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#21/250'
  },
  {
    tokenId: 1022,
    playerName: 'Alisson Becker',
    club: 'Liverpool',
    nationality: 'Brazil',
    rarity: 'Epic',
    rating: 89,
    position: 'GK',
    pace: 54,
    shooting: 25,
    passing: 86,
    dribbling: 55,
    defending: 90,
    physical: 85,
    ability: 'Guardian Reflexes',
    imageUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1022/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#22/250'
  },
  {
    tokenId: 1023,
    playerName: 'Pedri Gonzalez',
    club: 'Barcelona',
    nationality: 'Spain',
    rarity: 'Epic',
    rating: 87,
    position: 'CM',
    pace: 79,
    shooting: 75,
    passing: 89,
    dribbling: 90,
    defending: 70,
    physical: 72,
    ability: 'Golden Boy Flow',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1023/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#23/250'
  },
  {
    tokenId: 1024,
    playerName: 'Ruben Dias',
    club: 'Manchester City',
    nationality: 'Portugal',
    rarity: 'Epic',
    rating: 88,
    position: 'CB',
    pace: 67,
    shooting: 40,
    passing: 72,
    dribbling: 70,
    defending: 89,
    physical: 87,
    ability: 'Commanding Wall',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1024/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#24/250'
  },
  {
    tokenId: 1025,
    playerName: 'Rafael Leão',
    club: 'AC Milan',
    nationality: 'Portugal',
    rarity: 'Epic',
    rating: 87,
    position: 'LW',
    pace: 93,
    shooting: 82,
    passing: 79,
    dribbling: 89,
    defending: 30,
    physical: 78,
    ability: 'Surfing Stride',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1025/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#25/250'
  },

  // 26-38: Rare
  {
    tokenId: 1026,
    playerName: 'Martin Ødegaard',
    club: 'Arsenal',
    nationality: 'Norway',
    rarity: 'Rare',
    rating: 86,
    position: 'CAM',
    pace: 76,
    shooting: 81,
    passing: 88,
    dribbling: 87,
    defending: 64,
    physical: 67,
    ability: 'Captains Incision',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1026/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#26/500'
  },
  {
    tokenId: 1027,
    playerName: 'Trent Alexander-Arnold',
    club: 'Liverpool',
    nationality: 'England',
    rarity: 'Rare',
    rating: 86,
    position: 'RB',
    pace: 78,
    shooting: 75,
    passing: 91,
    dribbling: 81,
    defending: 78,
    physical: 74,
    ability: 'Whipped Cross',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1027/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#27/500'
  },
  {
    tokenId: 1028,
    playerName: 'Theo Hernandez',
    club: 'AC Milan',
    nationality: 'France',
    rarity: 'Rare',
    rating: 86,
    position: 'LB',
    pace: 94,
    shooting: 74,
    passing: 78,
    dribbling: 83,
    defending: 80,
    physical: 85,
    ability: 'Turbo Overlap',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1028/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#28/500'
  },
  {
    tokenId: 1029,
    playerName: 'Eduardo Camavinga',
    club: 'Real Madrid',
    nationality: 'France',
    rarity: 'Rare',
    rating: 85,
    position: 'CDM',
    pace: 82,
    shooting: 70,
    passing: 83,
    dribbling: 85,
    defending: 83,
    physical: 82,
    ability: 'Elastic Recovery',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1029/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#29/500'
  },
  {
    tokenId: 1030,
    playerName: 'Khvicha Kvaratskhelia',
    club: 'Napoli',
    nationality: 'Georgia',
    rarity: 'Rare',
    rating: 85,
    position: 'LW',
    pace: 86,
    shooting: 82,
    passing: 82,
    dribbling: 88,
    defending: 42,
    physical: 76,
    ability: 'Kvaradona Twirl',
    imageUrl: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1030/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#30/500'
  },
  {
    tokenId: 1031,
    playerName: 'Jeremie Frimpong',
    club: 'Bayer Leverkusen',
    nationality: 'Netherlands',
    rarity: 'Rare',
    rating: 85,
    position: 'RB',
    pace: 96,
    shooting: 74,
    passing: 80,
    dribbling: 86,
    defending: 75,
    physical: 72,
    ability: 'Wing Velocity',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1031/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#31/500'
  },
  {
    tokenId: 1032,
    playerName: 'Gavi Paez',
    club: 'Barcelona',
    nationality: 'Spain',
    rarity: 'Rare',
    rating: 85,
    position: 'CM',
    pace: 78,
    shooting: 72,
    passing: 83,
    dribbling: 86,
    defending: 76,
    physical: 82,
    ability: 'Fearless Warrior',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1032/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#32/500'
  },
  {
    tokenId: 1033,
    playerName: 'Gabriel Magalhães',
    club: 'Arsenal',
    nationality: 'Brazil',
    rarity: 'Rare',
    rating: 85,
    position: 'CB',
    pace: 74,
    shooting: 42,
    passing: 69,
    dribbling: 66,
    defending: 87,
    physical: 86,
    ability: 'Corner Bulwark',
    imageUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1033/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#33/500'
  },
  {
    tokenId: 1034,
    playerName: 'Ollie Watkins',
    club: 'Aston Villa',
    nationality: 'England',
    rarity: 'Rare',
    rating: 85,
    position: 'ST',
    pace: 87,
    shooting: 84,
    passing: 77,
    dribbling: 82,
    defending: 45,
    physical: 80,
    ability: 'Channel Runner',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1034/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#34/500'
  },
  {
    tokenId: 1035,
    playerName: 'Alexander Isak',
    club: 'Newcastle United',
    nationality: 'Sweden',
    rarity: 'Rare',
    rating: 85,
    position: 'ST',
    pace: 88,
    shooting: 84,
    passing: 75,
    dribbling: 86,
    defending: 35,
    physical: 74,
    ability: 'Nordic Grace',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1035/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#35/500'
  },
  {
    tokenId: 1036,
    playerName: 'Nicolo Barella',
    club: 'Inter Milan',
    nationality: 'Italy',
    rarity: 'Rare',
    rating: 86,
    position: 'CM',
    pace: 80,
    shooting: 78,
    passing: 85,
    dribbling: 85,
    defending: 79,
    physical: 81,
    ability: 'Sardinian Dynamo',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1036/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#36/500'
  },
  {
    tokenId: 1037,
    playerName: 'Alessandro Bastoni',
    club: 'Inter Milan',
    nationality: 'Italy',
    rarity: 'Rare',
    rating: 85,
    position: 'CB',
    pace: 75,
    shooting: 45,
    passing: 80,
    dribbling: 76,
    defending: 87,
    physical: 83,
    ability: 'Ball-Playing Commander',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1037/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#37/500'
  },
  {
    tokenId: 1038,
    playerName: 'Diogo Costa',
    club: 'FC Porto',
    nationality: 'Portugal',
    rarity: 'Rare',
    rating: 84,
    position: 'GK',
    pace: 55,
    shooting: 20,
    passing: 82,
    dribbling: 50,
    defending: 85,
    physical: 80,
    ability: 'Penalty Stopper',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1038/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#38/500'
  },

  // 39-50: Common
  {
    tokenId: 1039,
    playerName: 'Anthony Gordon',
    club: 'Newcastle United',
    nationality: 'England',
    rarity: 'Common',
    rating: 81,
    position: 'LW',
    pace: 89,
    shooting: 77,
    passing: 75,
    dribbling: 82,
    defending: 48,
    physical: 72,
    ability: 'Aggressive Drive',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1039/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#39/1000'
  },
  {
    tokenId: 1040,
    playerName: 'Micky van de Ven',
    club: 'Tottenham Hotspur',
    nationality: 'Netherlands',
    rarity: 'Common',
    rating: 82,
    position: 'CB',
    pace: 92,
    shooting: 40,
    passing: 72,
    dribbling: 73,
    defending: 82,
    physical: 83,
    ability: 'Recovery Sprint',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1040/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#40/1000'
  },
  {
    tokenId: 1041,
    playerName: 'Alejandro Garnacho',
    club: 'Manchester United',
    nationality: 'Argentina',
    rarity: 'Common',
    rating: 80,
    position: 'LW',
    pace: 88,
    shooting: 76,
    passing: 72,
    dribbling: 83,
    defending: 35,
    physical: 65,
    ability: 'Acrobatic Instinct',
    imageUrl: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1041/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#41/1000'
  },
  {
    tokenId: 1042,
    playerName: 'Kobbie Mainoo',
    club: 'Manchester United',
    nationality: 'England',
    rarity: 'Common',
    rating: 80,
    position: 'CM',
    pace: 72,
    shooting: 70,
    passing: 81,
    dribbling: 84,
    defending: 76,
    physical: 76,
    ability: 'Calm Composure',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1042/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#42/1000'
  },
  {
    tokenId: 1043,
    playerName: 'Pau Cubarsí',
    club: 'Barcelona',
    nationality: 'Spain',
    rarity: 'Common',
    rating: 80,
    position: 'CB',
    pace: 71,
    shooting: 35,
    passing: 83,
    dribbling: 75,
    defending: 82,
    physical: 74,
    ability: 'Laser Diagonal',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1043/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#43/1000'
  },
  {
    tokenId: 1044,
    playerName: 'Warren Zaïre-Emery',
    club: 'Paris Saint-Germain',
    nationality: 'France',
    rarity: 'Common',
    rating: 81,
    position: 'CM',
    pace: 78,
    shooting: 72,
    passing: 80,
    dribbling: 81,
    defending: 75,
    physical: 81,
    ability: 'Midfield Anchor',
    imageUrl: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1044/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#44/1000'
  },
  {
    tokenId: 1045,
    playerName: 'Bradley Barcola',
    club: 'Paris Saint-Germain',
    nationality: 'France',
    rarity: 'Common',
    rating: 81,
    position: 'LW',
    pace: 90,
    shooting: 76,
    passing: 77,
    dribbling: 84,
    defending: 40,
    physical: 68,
    ability: 'Direct Cut-Inside',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1045/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#45/1000'
  },
  {
    tokenId: 1046,
    playerName: 'Malo Gusto',
    club: 'Chelsea',
    nationality: 'France',
    rarity: 'Common',
    rating: 79,
    position: 'RB',
    pace: 86,
    shooting: 60,
    passing: 78,
    dribbling: 80,
    defending: 77,
    physical: 76,
    ability: 'Flank Engine',
    imageUrl: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1046/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#46/1000'
  },
  {
    tokenId: 1047,
    playerName: 'Rico Lewis',
    club: 'Manchester City',
    nationality: 'England',
    rarity: 'Common',
    rating: 79,
    position: 'RB',
    pace: 81,
    shooting: 66,
    passing: 80,
    dribbling: 82,
    defending: 76,
    physical: 64,
    ability: 'Inverted Catalyst',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1047/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#47/1000'
  },
  {
    tokenId: 1048,
    playerName: 'Dominik Szoboszlai',
    club: 'Liverpool',
    nationality: 'Hungary',
    rarity: 'Common',
    rating: 82,
    position: 'CM',
    pace: 83,
    shooting: 82,
    passing: 84,
    dribbling: 82,
    defending: 64,
    physical: 76,
    ability: 'Cannonball Volley',
    imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1048/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#48/1000'
  },
  {
    tokenId: 1049,
    playerName: 'Castello Lukeba',
    club: 'RB Leipzig',
    nationality: 'France',
    rarity: 'Common',
    rating: 79,
    position: 'CB',
    pace: 78,
    shooting: 38,
    passing: 72,
    dribbling: 71,
    defending: 81,
    physical: 79,
    ability: 'Stealth Tackle',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1049/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#49/1000'
  },
  {
    tokenId: 1050,
    playerName: 'Bart Verbruggen',
    club: 'Brighton',
    nationality: 'Netherlands',
    rarity: 'Common',
    rating: 79,
    position: 'GK',
    pace: 50,
    shooting: 20,
    passing: 80,
    dribbling: 50,
    defending: 80,
    physical: 76,
    ability: 'Sweeper Instinct',
    imageUrl: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&w=600&q=80',
    metadataUrl: 'ipfs://bafybeifai1050/metadata.json',
    contractAddress: MOCK_CONTRACT,
    chainId: MOCK_CHAIN_ID,
    status: 'preview',
    edition: '#50/1000'
  }
];

// Ensure all cards have id, cardId, and overallRating populated
export const ENRICHED_NFT_CARDS: NFTCard[] = NFT_CARDS_DATA.map(c => ({
  ...c,
  id: c.id || `nft-card-${c.tokenId}`,
  cardId: c.cardId || `FAI-${c.tokenId}`,
  overallRating: c.overallRating ?? c.rating
}));

export async function getNFTCards(rarityFilter?: NFTRarity | 'All', searchQuery?: string): Promise<NFTCard[]> {
  await new Promise(resolve => setTimeout(resolve, 80));
  let cards = [...ENRICHED_NFT_CARDS];

  if (rarityFilter && rarityFilter !== 'All') {
    cards = cards.filter(c => c.rarity === rarityFilter);
  }

  if (searchQuery && searchQuery.trim().length > 0) {
    const q = searchQuery.toLowerCase().trim();
    cards = cards.filter(c => 
      c.playerName.toLowerCase().includes(q) ||
      c.club.toLowerCase().includes(q) ||
      c.position.toLowerCase().includes(q) ||
      c.nationality.toLowerCase().includes(q) ||
      c.ability.toLowerCase().includes(q)
    );
  }

  return cards;
}

export async function getNFTById(tokenId: number): Promise<NFTCard | undefined> {
  await new Promise(resolve => setTimeout(resolve, 50));
  return ENRICHED_NFT_CARDS.find(c => c.tokenId === tokenId);
}

export const getAllNFTCards = getNFTCards;
